spring:
  data:
    mongodb:
      database: seshstorage
      host: ds233323.mlab.com
      port: 33323
      username: admin
      password: admin22
---
spring:
  profiles: integrationtest
  data:
    mongodb:
      database: seshstorage_test
      host: ds149954.mlab.com
      port: 49954
      username: test-user
      password: testuser1
