spring:
  data:
    mongodb:
      database: seshstorage
      host: ds233323.mlab.com
      port: 33323
      username: admin
      password: admin22

  output:
    ansi:
      enabled: always

---
spring:
  profiles: test
  data:
    mongodb:
      database: seshstorage_test
      host: ds149954.mlab.com
      port: 49954
      username: testuser
      password: testuser1
